site_name: Malbec Labs
site_url: https://docs.malbeclabs.com/
theme:
  name: material
  palette:
    scheme: slate
    primary: red
  features:
    - content.code.copy
    - navigation.sections    
nav:
  - Welcome: index.md
  - Connect: how-to-connect.md
markdown_extensions:
  - toc