name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
          name: github-pages
          retention-days: 1
      - run: tar \
            --dereference --hard-dereference \
            --directory "./site" \
            -cvf "/home/runner/work/_temp/artifact.tar" \
            --exclude=.git \
            --exclude=.github
        shell: /usr/bin/sh -e {0}
      - uses actions/upload-artifact@v4
        with:
          name: github-pages
          path: /home/runner/work/_temp/artifact.tar
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false
