name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install mkdocs-material 
      - run: mkdocs build
      - run: cd /home/runner/work/docs/docs/site && tar --dereference -cvf "/home/runner/work/_temp/artifact.tar" .
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: /home/runner/work/_temp/artifact.tar
          retention-days: 1
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false
      - uses: actions/deploy-pages@v4
        with:
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false
